---
- name: install nginx
  become: true
  dnf:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  loop:
    - { name: 'nginx', state: 'latest' }
    - { name: 'php', state: 'latest' }
  tags:
    - web
    - nginx

- name: enable and start nginx
  become: true
  service:
    name: nginx
    state:  started
    enabled: yes
  tags:
    - web
    - nginx

- name: configure nginx
  become: true
  template:
    src: index.html.j2
    dest: /usr/share/nginx/html/index.html
    mode: 0644
  tags:
    - web
    - nginx

- name: add web services to firewall
  become: true
  ansible.posix.firewalld:
    zone: public
    service: "{{ item }}"
    permanent: yes
    state: enabled
  loop: 
    - "http"
    - "https"
  tags:
    - web
    - firewall
  notify:
    - restart firewall