---
- name: Configure DB Servers
  hosts: DB
  tasks:
    - name: db
      block:
        - import_role:
            name: _init
            tasks_from: firewall
      rescue:
        - name: print error message
          debug:
            msg: "Failed"
...