name: Ansible

on:
  pull_request:
    paths:
      - '**.yaml'

jobs:
  build:
    name: 'Ansible'
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

      # Runs Ansible Lint
    - name: Lint Ansible Playbook
      uses: ansible/ansible-lint-action@master
      with:
        # Paths to ansible files (i.e., playbooks, tasks, handlers etc..)
        # or valid Ansible directories according to the Ansible role
        # directory structure.
        targets: "./"
        # Arguments to be passed to the ansible-lint
        # Options:
        #   -q                    quieter, although not silent output
        args: "-q"