name: Ansible

on:
  pull_request:
    paths:
      - '**.yaml'

jobs:
  build:
    name: 'Ansible'
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

    # Setup Python
    - name: 'Setup Python'
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    # Install Dependencies
    - name: 'Install Ansible and Ansible Lynt'
      run: |
        python -m pip install --upgrade pip
        pip install ansible ansible-lint
    # Run Ansible Lint
    - name: 'Lint Ansible'
      run: |
        ansible-lint -q
