name: ChefInSpec

on:
  pull_request:
    paths:
      - '**.rb'

jobs:
  build:
    name: 'ChefInspec'
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

    # Install Chef
    - name: 'Install Chef Inspec'
      run: |
        curl https://omnitruck.chef.io/install.sh | sudo bash -s -- -P inspec
  
    # Run Ansible Lint
    - name: 'Execute Chef Inspec Check'
      run: |
        for d in ./inspec/*/; inspec check --chef-license=accept-silent $d
